/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaSwingRgbCmykConversion;

import java.awt.Color;
import java.lang.Math;

/**
 *
 * @author FerdiKT
 */
public final class MainFrame extends javax.swing.JFrame {

    double c, m, y, k,r, g, b;

    /**
     * Creates new form RGBChange
     */
    public MainFrame() {
        initComponents();
        CMYKConversion();
        RGBConversion();
    }

    public void CMYKConversion() {
        rColor.setText(String.valueOf(jSlider1.getValue()));
        r = jSlider1.getValue();
        gColor.setText(String.valueOf(jSlider2.getValue()));
        g = jSlider2.getValue();
        bColor.setText(String.valueOf(jSlider3.getValue()));
        b = jSlider3.getValue();
        
        //Set to CMYK
        double R=r/255,G = g/255,B = b/255;
        if (R<G) {
            R=G;
        }
        k = 1- Math.max(R, B);
        c = (1-R-k) / (1-k);
        m = (1-G-k) / (1-k);
        y = (1-B-k) / (1-k);
        
        jSlider4.setValue((int) (c * 1000));
        cColor.setText(String.valueOf(c));
        jSlider5.setValue((int) (m * 1000));
        mColor.setText(String.valueOf(m));
        jSlider6.setValue((int) (y * 1000));
        yColor.setText(String.valueOf(y));
        jSlider7.setValue((int) (k * 1000));
        kColor.setText(String.valueOf(k));
        
        this.getContentPane().setBackground(new Color((int)r, (int)g, (int)b));
        author.setForeground(new Color(255-(int)r, 255-(int)g, 255-(int)b));
    }

    public void RGBConversion() {
        c = (double)jSlider4.getValue() / 1000;
        cColor.setText(String.valueOf(c));
        m = (double)jSlider5.getValue() / 1000;
        mColor.setText(String.valueOf(m));
        y = (double)jSlider6.getValue() / 1000;
        yColor.setText(String.valueOf(y));
        k = (double)jSlider7.getValue() / 1000;
        kColor.setText(String.valueOf(k));
        
        r = (int) (255 * (1 - c) * (1 - k));
        g = (int) (255 * (1 - m) * (1 - k));
        b = (int) (255 * (1 - y) * (1 - k));
        
        rColor.setText(String.valueOf(r));
        jSlider1.setValue((int)r);
        gColor.setText(String.valueOf(g));
        jSlider2.setValue((int)g);
        bColor.setText(String.valueOf(b));
        jSlider3.setValue((int)b);
        
        this.getContentPane().setBackground(new Color((int)r, (int)g, (int)b));
        author.setForeground(new Color(255-(int)r, 255-(int)g, 255-(int)b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        rColor = new javax.swing.JLabel();
        gColor = new javax.swing.JLabel();
        bColor = new javax.swing.JLabel();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        cColor = new javax.swing.JLabel();
        mColor = new javax.swing.JLabel();
        yColor = new javax.swing.JLabel();
        jSlider7 = new javax.swing.JSlider();
        kColor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        author = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider1.setMaximum(255);
        jSlider1.setValue(0);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                redColorChange(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jSlider2.setMaximum(255);
        jSlider2.setValue(0);
        jSlider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                GreenColorChange(evt);
            }
        });
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, -1, -1));

        jSlider3.setMaximum(255);
        jSlider3.setValue(0);
        jSlider3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BlueColorChange(evt);
            }
        });
        getContentPane().add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, -1, -1));

        rColor.setText("jLabel1");
        getContentPane().add(rColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 20, -1, 29));

        gColor.setText("jLabel1");
        getContentPane().add(gColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 55, -1, 29));

        bColor.setText("jLabel1");
        getContentPane().add(bColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 90, -1, 29));

        jSlider4.setMaximum(1000);
        jSlider4.setValue(500);
        jSlider4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CChange(evt);
            }
        });
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 20, -1, -1));

        jSlider5.setMaximum(1000);
        jSlider5.setValue(500);
        jSlider5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MChange(evt);
            }
        });
        getContentPane().add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 55, -1, -1));

        jSlider6.setMaximum(1000);
        jSlider6.setToolTipText("");
        jSlider6.setValue(500);
        jSlider6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                YChange(evt);
            }
        });
        getContentPane().add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 90, -1, -1));

        cColor.setText("jLabel1");
        getContentPane().add(cColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 20, -1, 29));

        mColor.setText("jLabel1");
        getContentPane().add(mColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 55, -1, 29));

        yColor.setText("jLabel1");
        getContentPane().add(yColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 90, -1, 29));

        jSlider7.setMaximum(1000);
        jSlider7.setToolTipText("");
        jSlider7.setValue(500);
        jSlider7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                KChange(evt);
            }
        });
        getContentPane().add(jSlider7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 125, -1, -1));

        kColor.setText("jLabel1");
        getContentPane().add(kColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 125, -1, 29));

        jLabel8.setText("G");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, -1, 29));

        jLabel9.setText("B");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 9, 29));

        jLabel10.setText("R");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, -1, 29));

        jLabel11.setText("C");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 20, -1, 29));

        jLabel12.setText("M");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 55, -1, 29));

        jLabel13.setText("Y");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 90, -1, 29));

        jLabel14.setText("K");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 125, -1, 29));

        author.setText("Ferdi Kızıltoprak");
        getContentPane().add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redColorChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redColorChange
        CMYKConversion();
    }//GEN-LAST:event_redColorChange

    private void GreenColorChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GreenColorChange
        CMYKConversion();
    }//GEN-LAST:event_GreenColorChange

    private void BlueColorChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlueColorChange
        CMYKConversion();
    }//GEN-LAST:event_BlueColorChange

    private void CChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CChange
        RGBConversion();
    }//GEN-LAST:event_CChange

    private void MChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MChange
        RGBConversion();
    }//GEN-LAST:event_MChange

    private void YChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YChange
        RGBConversion();
    }//GEN-LAST:event_YChange

    private void KChange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KChange
        RGBConversion();
    }//GEN-LAST:event_KChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JLabel bColor;
    private javax.swing.JLabel cColor;
    private javax.swing.JLabel gColor;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JLabel kColor;
    private javax.swing.JLabel mColor;
    private javax.swing.JLabel rColor;
    private javax.swing.JLabel yColor;
    // End of variables declaration//GEN-END:variables
}
